### ISSUE TITLE
Upload a modified version of an image.

### ISSUE THREAD

**Issue by surveyor54** [trougnouf/dtMediaWiki#9] opened 2021-02-07 15:09 UTC
Hi,
could someone explain to me, how to upload a modified version of an image. I have already tried everything. Where do you enter "alt: filename"?

Greetings
surveyor54

**Comment by trougnouf** [comment] 2021-02-07 15:38
The alt:<filename> is used to link different images together in an "other versions" gallery. What you described (different versions of the same source file) might work or would need to be implemented, but it hasn't been tested.

For example in https://commons.wikimedia.org/wiki/File:Facade_of_the_Aulne_Abbey_during_golden_hour_(DSC_0123).jpg , I added "alt:DSC 0136" as a tag (the same way I added "Category:Abbaye d'Aulne").

dtMediaWiki tries to match images from the current library ( https://github.com/trougnouf/dtMediaWiki/blob/master/dtMediaWiki.lua , function get_alt_images) with the given "alt:<>" tags. Because there is no break in the search, I believe it might still work in your use-case and find multiple versions of itself.

To test this you need to **add in the "alt:filename" tag**, and **the title** (or whatever is used to generate a Wikimedia filename) **must be different in both versions** (otherwise it would just generate the same wiki filename and link the same picture twice).

If this doesn't work it might be best to implement an alternative where the user has to manually enter the darktable image id.

**Comment by surveyor54** [comment] 2021-02-07 21:58
Thank you for your fast answer.
It doesn't work. I hope I made no mistake.
It's about this picture. https://commons.wikimedia.org/wiki/File:Gettenbach_ND_435184_1.jpg
I only wrote **alt:ND 435184 2** and **Category:Natural heritage in Gründau** in the tag-window.
The other entries I did not change but nothing happend.

**Comment by trougnouf** [comment] 2021-02-08 10:02
I just tested it with https://commons.wikimedia.org/wiki/File:Rundberg_Running_Man_duplicate_test_(GEDC9295).jpg and it seems to work. (it added some files that I didn't want to the gallery but that's because I was working on a huge library in the current view, that wouldn't happen in a normal use-case)

Two things that may have gone wrong:

Did you make a duplicate of the image in darktable? It's important that there are different images matching the given filename, dtMediaWiki will determine the Wikimedia titles from there (otherwise there will just be a gallery with the current version of the image).

In the screenshot it looks like you have a space after "alt:" before the filename. This would prevent it from finding the file because get_alt_images will look for any filename that contains " ND 435184 1" (with the leading space). Better not enough characters than too many. You could try with "alt:ND 435184".

**Comment by surveyor54** [comment] 2021-02-10 16:07
Hi,
I can't get this right, my be, I am too old. 
Let me explain my process again.
I have uploaded an image with the name **hallo_01.jpg.**

Now I have created a duplicate in darktable and croped it a bit.

What does **alt:** mean: ? 
I think alternative or?

I left everything in the duplicate as it was in the original and entered only **alt:hallo**  in the tags window. 

> Better not enough characters than too many.

I hope I have understood this correctly.

Nothing happened again.  :(

I would like to understand it, if you don't mind, please try to explain it step by step.

Thanks and greetings
surveyor54

**Comment by trougnouf** [comment] 2021-02-10 17:56
alt: stands for alternate indeed.

The duplicate should have a different "title" if that's what's used to generate the Wikimedia filename (otherwise it should show the same filename twice on Wikimedia; darktable does not duplicate the actual source file).

I saw on https://commons.wikimedia.org/wiki/File:Lettgenbrunn_02.jpg that the "Other versions: " had a gallery, so the "alt:" tag did trigger the "get_alt_images" function, but no matching images were found in the current library (hence empty gallery).

How do you generate the filename? I think the default **naming pattern** in dtMediaWiki is "$TITLE ($FILE_NAME)". It would need to have an auto-generated part that differs between the two versions (s.a. $TITLE).

How do you open the image? The two versions should be in the same current library; so you would browse them in lighttable (eg by opening the folder there), and export one of them from there. (As opposed to opening an image with darktable from the file browser; then I don't know what the current library would be made of.)

Are you able to launch darktable from the terminal ?
If so can you update to the latest version [(dtMediaWiki.lua)](https://raw.githubusercontent.com/trougnouf/dtMediaWiki/master/dtMediaWiki.lua) and run darktable as `darktable -d lua` ? I've added a bunch of debug messages in get_alt_images that will show up in the terminal then.

Then the matching process will be shown and results in something like the following when there is no match:
```
[...]
24.193014 LUA dtMediaWiki.get_alt_images: looking at GEDC9283.JPG
24.193024 LUA dtMediaWiki.get_alt_images: looking for GEDC9295
[...]
```
and the following when there is one:
```
[...]
24.216731 LUA dtMediaWiki.get_alt_images: looking at GEDC9295.JPG
24.216741 LUA dtMediaWiki.get_alt_images: looking for GEDC9295
24.216869 LUA dtMediaWiki.get_alt_images: found Rundberg Running Man (GEDC9295).jpg
24.218331 LUA dtMediaWiki.get_alt_images: looking at GEDC9295.JPG
24.218339 LUA dtMediaWiki.get_alt_images: looking for GEDC9295
24.218465 LUA dtMediaWiki.get_alt_images: found Rundberg Running Man duplicate test (GEDC9295).jpg
[...]
```

**Comment by surveyor54** [comment] 2021-02-11 10:00
Thanks for your effort and patience, I got it. :+1: 
```
.....
547,303932 LUA dtMediaWiki.get_alt_images: looking at 7395.JPG
547,303950 LUA dtMediaWiki.get_alt_images: looking for 7395
547,304218 LUA dtMediaWiki.get_alt_images: found Lettgenbrunn Gedenkstein crop(7395).jpg
547,304426 LUA dtMediaWiki.get_alt_images: looking at 7395.JPG
547,304436 LUA dtMediaWiki.get_alt_images: looking for 7395
547,304693 LUA dtMediaWiki.get_alt_images: found Lettgenbrunn Gedenkstein(7395).jpg
......
```
My mistakes were that I didn't create a duplicate and made a mistake with the naming pattern.
This is now the connection of the image with other versions.


I hope I'm not annoying, I now have one more question.

How do I now **replace** the current version with a new changed one? 
Is that also feasible?

Thanks and greetings
surveyor54

**Comment by trougnouf** [comment] 2021-02-11 10:07
So that worked? Excellent :)

You can replace an image by exporting it with the same Wikimedia filename (title), just make sure that "Commons: Overwrite existing images" is toggled in the darktable lua settings.
The Wikimedia page's code won't be updated, only the actual image will.

**Comment by surveyor54** [comment] 2021-02-11 10:52
It works perfectly. :+1: 

Thank you and have a good time.
surveyor54

**Closed** 2023-11-10 15:00 UTC
